name: "RecipesRedone"
author: TheTealViper
version: "1.21.0.b.1"
api-version: "1.21"
description: "Redo recipes"
main: me.TheTealViper.recipesredone.RecipesRedone
commands:
 createrecipe:
  permission: "recipesredone.createrecipe"
 loadrecipes:
  permission: "recipesredone.loadrecipes"